"""Add yt_link column to MyModel

Revision ID: 35a4245e89c4
Revises: 67cb4f637077
Create Date: 2023-03-30 11:49:53.959428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35a4245e89c4'
down_revision = '67cb4f637077'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('yt_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'yt_link')
    # ### end Alembic commands ###
