"""seed.py started

Revision ID: 10acb35a1edb
Revises: fc8312a0ec02
Create Date: 2023-03-28 15:20:54.637325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10acb35a1edb'
down_revision = 'fc8312a0ec02'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('artist_id', sa.Integer(), nullable=True))
    op.add_column('songs', sa.Column('listener_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'songs', 'artists', ['artist_id'], ['id'])
    op.create_foreign_key(None, 'songs', 'listeners', ['listener_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'songs', type_='foreignkey')
    op.drop_constraint(None, 'songs', type_='foreignkey')
    op.drop_column('songs', 'listener_id')
    op.drop_column('songs', 'artist_id')
    # ### end Alembic commands ###
