"""update tables

Revision ID: 1ab9cfdc5dae
Revises: 10acb35a1edb
Create Date: 2023-03-29 10:02:52.962510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ab9cfdc5dae'
down_revision = '10acb35a1edb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('genre', sa.String(), nullable=True))
    op.add_column('artists', sa.Column('founded', sa.Integer(), nullable=True))
    op.add_column('listeners', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('songs', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('songs', sa.Column('stream_count', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'songs', 'artists', ['artist_id'], ['id'])
    op.create_foreign_key(None, 'songs', 'listeners', ['listener_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'songs', type_='foreignkey')
    op.drop_constraint(None, 'songs', type_='foreignkey')
    op.drop_column('songs', 'stream_count')
    op.drop_column('songs', 'year')
    op.drop_column('listeners', 'age')
    op.drop_column('artists', 'founded')
    op.drop_column('artists', 'genre')
    # ### end Alembic commands ###
