"""join table added

Revision ID: 3921e7886b7c
Revises: fbcb4591a47d
Create Date: 2023-03-29 19:28:57.759220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3921e7886b7c'
down_revision = 'fbcb4591a47d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('song_listeners',
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('listener_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['listener_id'], ['listeners.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('song_id', 'listener_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('song_listeners')
    # ### end Alembic commands ###
