"""Added basic models

Revision ID: ee1b00ad5b91
Revises: e2eb75390f23
Create Date: 2023-03-28 09:38:41.080279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee1b00ad5b91'
down_revision = 'e2eb75390f23'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
